--%pattern=sale_billdata_
--%
(
	BILL INTEGER PRIMARY KEY CHECK(BILL BETWEEN 0 AND 9999),
	ALIAS TEXT(20) REFERENCES party_db(ALIAS),
	INVOICE_DATE TEXT(10) CHECK(INVOICE_DATE LIKE '__/__/____'),
	CHL_NO INTEGER,
	CHL_DT TEXT(10),
	PO_DT TEXT(10),
	PO_NO TEXT(20),
	NARR TEXT(100)
	)
--%

--%pattern=sale_fulldata_
--%
(
	TID INTEGER PRIMARY KEY AUTOINCREMENT,
	BILL INTEGER REFERENCES sale_billdata(BILL),
	SR_NO INTEGER CHECK(SR_NO BETWEEN 0 AND 999),
	PID TEXT(20) REFERENCES product_db(PID),
	QTY INTEGER CHECK(QTY BETWEEN 0 AND 99999),
	RATE REAL CHECK(RATE >= 0),
	DISC INTEGER CHECK(DISC BETWEEN 0 AND 100),
	GST INTEGER CHECK(GST BETWEEN 0 AND 100),
	BATCH TEXT(20),
	EXPIRY TEXT(7),
	MRP REAL CHECK(MRP >= 0),
	UNIQUE(BILL, SR_NO)
	)
--%

--%pattern=sale_payments_
--%
(
	PAY_ID INTEGER PRIMARY KEY AUTOINCREMENT,
	PAY_DATE TEXT(10) CHECK(PAY_DATE LIKE '__/__/____'),
	ALIAS TEXT(20) REFERENCES party_db(ALIAS),
	AMOUNT REAL CHECK(AMOUNT >= 0),
	PAY_MODE TEXT(20),
	REMARKS TEXT(100)
	)
--%

--%pattern=purc_billdata_
--%
(
	BILL INTEGER PRIMARY KEY CHECK(BILL BETWEEN 0 AND 9999),
	INVOICE_DATE TEXT(10) CHECK(INVOICE_DATE LIKE '__/__/____'),
	ALIAS TEXT(20) REFERENCES party_db(ALIAS),
	CHL_NO INTEGER,
	CHL_DT TEXT(10),
	PO_DT TEXT(10),
	PO_NO TEXT(20),
	NARR TEXT(100)
	)
--%

--%pattern=purc_fulldata_
--%
(
	TID INTEGER PRIMARY KEY AUTOINCREMENT,
	BILL INTEGER REFERENCES purc_billdata(BILL),
	SR_NO INTEGER CHECK(SR_NO BETWEEN 0 AND 999),
	PID TEXT(20) REFERENCES product_db(PID),
	QTY INTEGER CHECK(QTY BETWEEN 0 AND 99999),
	RATE REAL CHECK(RATE >= 0),
	DISC INTEGER CHECK(DISC BETWEEN 0 AND 100),
	GST INTEGER CHECK(GST BETWEEN 0 AND 100),
	BATCH TEXT(20),
	EXPIRY TEXT(7),
	MRP REAL CHECK(MRP >= 0),
	UNIQUE(BILL, SR_NO)
	)
--%

--%pattern=purc_payments_
--%
(
	PAY_ID INTEGER PRIMARY KEY AUTOINCREMENT,
	PAY_DATE TEXT(10) CHECK(PAY_DATE LIKE '__/__/____'),
	ALIAS TEXT(20) REFERENCES party_db(ALIAS),
	AMOUNT REAL CHECK(AMOUNT >= 0),
	PAY_MODE TEXT(20),
	REMARKS TEXT(100)
	)
--%
