--%table=product_db
--%
CREATE TABLE IF NOT EXISTS product_db (
	PID TEXT(20) PRIMARY KEY,
	PRODUCT_NAME TEXT(100) NOT NULL,
	UNIT TEXT(20),
	HSN_CODE INTEGER,
	MFG TEXT(20),
	GST_D REAL
)
--%

--%table=fy_list
--%
CREATE TABLE IF NOT EXISTS fy_list (
	FY_ID TEXT(20) PRIMARY KEY,
	FY_NAME TEXT(50)
)
--%

--%table=party_db
--%
CREATE TABLE IF NOT EXISTS party_db (
	ALIAS TEXT(20) PRIMARY KEY,
	PARTY_NAME TEXT(100) NOT NULL,
	ACC_TYPE TEXT(4) CHECK(ACC_TYPE IN ('sale', 'purc')),
	CONTACT_NO1 INTEGER CHECK(LENGTH(CONTACT_NO1) <= 13),
	CONTACT_NO2 INTEGER CHECK(LENGTH(CONTACT_NO2) <= 13),
	EMAIL_ID TEXT(100),
	ADDRESS_LINE1 TEXT(100),
	ADDRESS_LINE2 TEXT(100),
	ADDRESS_LINE3 TEXT(100),
	STATE TEXT(50),
	GSTIN_NO1 TEXT(50),
	GSTIN_NO2 TEXT(50),
	PINCODE INTEGER CHECK(LENGTH(PINCODE) = 6)
)
--%

--%table=stock_db
--%
CREATE TABLE IF NOT EXISTS stock_db (
	SID INTEGER PRIMARY KEY AUTOINCREMENT,
	PID TEXT(20) REFERENCES product_db(PID),
	BATCH TEXT(20),
	EXPIRY TEXT(7),
	MRP REAL CHECK(MRP >= 0),
	BAL INTEGER,
	UNIQUE(PID, BATCH)
	)
--%
